---
abstract: 'monkey-patch DBIx::Simple to use SQL::Interpol'
author:
  - 'Aristotle Pagaltzis <pagaltzis@gmx.de>'
build_requires:
  File::Find: 0
  File::Temp: 0
  Test::More: 0.88
  lib: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.029, CPAN::Meta::Converter version 2.143240'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: DBIx-Simple-Interpol
requires:
  DBIx::Simple: 0
  Exporter::Tidy: 0
  SQL::Interpol: 0
  strict: 0
  warnings: 0
resources:
  bugtracker: http://github.com/ap/DBIx-Simple-Interpol/issues
  homepage: http://github.com/ap/DBIx-Simple-Interpol
  repository: git://github.com/ap/DBIx-Simple-Interpol
version: 1.003
